# Generated by Django 5.2.3 on 2025-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_categories', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['main_category'], name='catalog_pro_main_ca_20eac9_idx'), models.Index(fields=['sub_categories'], name='catalog_pro_sub_cat_c19419_idx'), models.Index(fields=['product_title'], name='catalog_pro_product_fa407a_idx')],
            },
        ),
    ]
