# Generated by Django 4.2.21 on 2025-06-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_main_ca_ed3ed9_idx',
            old_name='catalog_pro_main_ca_20eac9_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_sub_cat_7ec3bd_idx',
            old_name='catalog_pro_sub_cat_c19419_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_product_689b66_idx',
            old_name='catalog_pro_product_fa407a_idx',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
