# Generated by Django 5.2.3 on 2025-06-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_pro_main_ca_20eac9_idx_products_main_ca_ed3ed9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
