# Generated by Django 5.2.3 on 2025-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('cxml_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.CharField(blank=True, max_length=255)),
                ('punchout_request_url', models.CharField(blank=True, max_length=500)),
                ('punchout_response_url', models.CharField(blank=True, max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
            ],
            options={
                'db_table': 'punchout_orders',
            },
        ),
        migrations.DeleteModel(
            name='PunchOutSession',
        ),
    ]
